# Lets upgrade Day-3 Data Science Assignment

#  Question-1
       
       Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [2]:
import numpy as np

In [10]:
arr=np.arange(2,53,3)
arr


array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

#  Question-2
     
       Accept two lists of 5 elements each from the user.
       Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [17]:
x=[]
y=[]
for _ in range(0,5):
    i = int(input())
    x.append(i)
for _ in range(0,5):
    j = int(input())
    y.append(j)
arr1 = np.array(x)
arr2 = np.array(y)
arr = np.concatenate((arr1,arr2))
print("the concatenated array :",arr)
arr3 = np.sort(arr)
print("the sorted array :",arr3)
    

0
4
5
6
3
2
1
7
8
9
the concatenated array : [0 4 5 6 3 2 1 7 8 9]
the sorted array : [0 1 2 3 4 5 6 7 8 9]


#   Question-3
    
         Write a code snippet to find the dimensions of a ndarray and its size.

In [33]:
def array():
    arr=np.random.rand(2,5)
    print(arr)
    print("the no of dimensions are :",arr.ndim)
    print("the size of array is :",arr.size)
array()    
    


[[0.05648626 0.19615525 0.2684978  0.53821812 0.88683218]
 [0.6384026  0.30048658 0.84413157 0.7620633  0.86528177]]
the no of dimensions are : 2
the size of array is : 10


# Question-4
      
      How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet.
      (Hint: np.newaxis, np.expand_dims)

In [46]:
# convertion of 1d-2d array :

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = np.reshape(arr, (2, 5))
print(arr)
print(arr_2d)
print("\n")

#demonstration of np.newaxis & np.expand_dims :

arr = np.arange(5*5).reshape(5, 5) 
print(arr.shape) 
arr_5D = arr[np.newaxis,np.newaxis] 
print(arr_5D.shape)
print("\n")

x = np.zeros((3, 4)) 
y = np.expand_dims(x, axis=2).shape 
print(y) 



[[0 1 2 3 4]
 [5 6 7 8 9]]


(5, 5)
(1, 1, 5, 5)


(3, 4, 1)


# Question-5
      
      Consider two square numpy arrays. Stack them vertically and horizontally.
      (Hint: Use vstack(), hstack())

In [53]:
arr1 = np.array([ 1, 2, 3] ) 
print ("1st Input array : ", arr1)  
  
arr2 = np.array([ 4, 5, 6] ) 
print ("2nd Input array : ", arr2)  

out_arr = np.hstack((arr1, arr2)) 
print ("horizontally stacked array is :\n ", out_arr) 

out_arr1 = np.vstack((arr1, arr2)) 
print ("\nOutput vertically stacked array: \n", out_arr1) 


1st Input array :  [1 2 3]
2nd Input array :  [4 5 6]
horizontally stacked array is :
  [1 2 3 4 5 6]

Output vertically stacked array: 
 [[1 2 3]
 [4 5 6]]


# Question-6

      How to get unique items and counts of unique items?

In [70]:
x = []
n = int(input("enter no of inputs you want to give :"))
for i in range(0, n): 
    a = int(input())
    x.append(a)
y = [] 
for item in x: 
    if item not in y: 
        y.append(item) 
print("\nOriginal list :",x)
print("\nNumber of unique elements- "+str(len(y)))
print("\nlist containing only unique elements :",y)

enter no of inputs you want to give :5
1
1
2
2
3

Original list : [1, 1, 2, 2, 3]

Number of unique elements- 3

list containing only unique elements : [1, 2, 3]
